import React,{memo,useCallback,useEffect,useMemo,useState}from'react';
import{uid,today,TL,trDate,addMonths,fee,clientRow,statusLabel,validDate,money,expensesFor}from'./clients-domain.js';
import{makePdf,makeExcel}from'./clients-export.js';
import'./clients.css';
const EMPTY_CLIENTS=[];
const PAGE_SIZE=24;
function useToday(){
  const [day,setDay]=useState(today);
  useEffect(()=>{
    let timer;
    function refresh(){
      setDay(today());
      clearTimeout(timer);
      const now=new Date();
      timer=setTimeout(refresh,new Date(now.getFullYear(),now.getMonth(),now.getDate()+1)-now+100);
    }
    refresh();
    window.addEventListener('focus',refresh);
    document.addEventListener('visibilitychange',refresh);
    return()=>{clearTimeout(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)};
  },[]);
  return day;
}
export default function ClientTracker({state,setState}){const[open,setOpen]=useState(false),[selected,setSelected]=useState(null),[edit,setEdit]=useState(null),[periodEdit,setPeriodEdit]=useState(null),[query,setQuery]=useState(''),[expenseEdit,setExpenseEdit]=useState(null);const day=useToday();
const clients=state.clients||EMPTY_CLIENTS;
const rows=useMemo(()=>open?clients.map(c=>clientRow(c,state.settings,day)):[],[open,clients,state.settings,day]);
const filtered=useMemo(()=>{
  const search=query.toLocaleLowerCase('tr-TR');
  return search?rows.filter(c=>`${c.name} ${c.workType||''}`.toLocaleLowerCase('tr-TR').includes(search)):rows;
},[rows,query]);
const totals=useMemo(()=>rows.reduce((a,c)=>(a.accrued+=c.accrued+c.expenseTotal,a.paid+=c.paid+c.expensePaid,a.balance+=c.balance,a.late+=c.late,a),{accrued:0,paid:0,balance:0,late:0}),[rows]);
const back=useCallback(()=>setSelected(null),[]);
const select=useCallback(c=>setSelected(c.id),[]);
const add=useCallback(()=>setEdit({}),[]);
const editCurrent=useCallback(()=>setEdit(clients.find(c=>c.id===selected)),[clients,selected]);
const setSettings=useCallback(v=>setState(s=>({...s,settings:{...s.settings,...v}})),[]);
const saveExpense=useCallback((clientId,entry)=>{
  setState(s=>({...s,clients:s.clients.map(c=>c.id!==clientId?c:{...c,expenses:entry.id?(c.expenses||[]).map(e=>e.id===entry.id?{...e,...entry}:e):[{...entry,id:uid()},...(c.expenses||[])]})}));
  setExpenseEdit(null);
},[setState]);
function saveClient(c){setState(s=>({...s,clients:c.id?s.clients.map(x=>x.id===c.id?{...x,...c}:x):[{...c,id:uid(),periods:[],createdAt:new Date().toISOString()},...s.clients]}));setEdit(null)}function updatePeriod(client,key,patch){setState(s=>({...s,clients:s.clients.map(c=>c.id!==client.id?c:{...c,periods:[...(c.periods||[]).filter(p=>p.key!==key),{...(c.periods||[]).find(p=>p.key===key),key,...patch}]})}));setPeriodEdit(null)}if(!open)return <button className="clientLauncher" onClick={()=>setOpen(true)}>⚖ Müvekkiller</button>;const current=selected?rows.find(c=>c.id===selected):null;return <div className="clientOverlay"><div className="clientApp"><header className="clientHeader"><div><small>BT · AVUKATLIK</small><b>Müvekkil & Tahsilat Takibi</b></div><button onClick={()=>{setOpen(false);setSelected(null)}}>✕</button></header>{current?<ClientDetail c={current} settings={state.settings} key={current.id} back={back} edit={editCurrent} periodEdit={setPeriodEdit} expenseEdit={setExpenseEdit} day={day}/>:<ClientHome rows={filtered} totals={totals} query={query} setQuery={setQuery} select={select} add={add} settings={state.settings} setSettings={setSettings}/>} {edit&&<ClientForm initial={edit} settings={state.settings} close={()=>setEdit(null)} save={saveClient}/>} {periodEdit&&<PeriodForm data={periodEdit} close={()=>setPeriodEdit(null)} save={patch=>updatePeriod(periodEdit.client,periodEdit.period.key,patch)}/>} {expenseEdit&&<ExpenseForm initial={expenseEdit.expense||{}} close={()=>setExpenseEdit(null)} save={entry=>saveExpense(expenseEdit.clientId,entry)}/>}</div></div>}
const ClientHome=memo(function ClientHome({rows,totals,query,setQuery,select,add,settings,setSettings}){return <main className="clientMain"><div className="clientPageTitle"><div><small>CARİ TAKİP</small><h1>Müvekkiller</h1></div><button className="clientPrimary" onClick={add}>＋ Müvekkil</button></div><div className="clientKpis"><K label="Hizmet + masraf" value={TL(totals.accrued)}/><K label="Tahsil Edilen" value={TL(totals.paid)} tone="good"/><K label="Açık Bakiye" value={TL(totals.balance)} tone="bad"/><K label="Gecikmiş" value={TL(totals.late)} tone="bad"/></div><section className="clientSettings"><b>Ücret Hesabı</b><label>Asgari ücret baz tutarı<input type="number" value={settings.minimumWage} onChange={e=>setSettings({minimumWage:Math.max(0,Number(e.target.value)||0)})}/></label><label>Varsayılan KDV %<input type="number" value={settings.vatRate} onChange={e=>setSettings({vatRate:Math.max(0,Number(e.target.value)||0)})}/></label></section><div className="clientSearch"><input placeholder="Müvekkil veya iş ara" value={query} onChange={e=>setQuery(e.target.value)}/></div><section className="clientList">{!rows.length&&<div className="clientEmpty">Henüz müvekkil kaydı yok.</div>}{rows.map(c=><button className="clientCard" key={c.id} onClick={()=>select(c)}><div><b>{c.name}</b><small>{c.workType||'Hukuki hizmet'} · {c.active===false?'Pasif':'Aktif'}</small><span>{trDate(c.startDate)} başlangıç</span></div><div><strong className={c.balance>0?'bad':'good'}>{TL(c.balance)}</strong><small>Açık bakiye</small><span>{c.late>0?`${TL(c.late)} gecikmiş`:'Gecikme yok'}</span></div></button>)}</section></main>});
function K({label,value,tone=''}){return <div className="clientKpi"><small>{label}</small><b className={tone}>{value}</b></div>}
const ClientDetail=memo(function ClientDetail({c,settings,back,edit,periodEdit,expenseEdit,day}){const {accrued,paid,balance}=c;const [visibleCount,setVisibleCount]=useState(PAGE_SIZE);const visiblePeriods=useMemo(()=>c.ps.slice().reverse().slice(0,visibleCount),[c.ps,visibleCount]);
const [exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
async function exportDocument(make){
  setExporting(true);setExportError('');
  try{await make(c,settings)}catch{setExportError('Belge oluşturulamadı. Lütfen tekrar deneyin.')}finally{setExporting(false)}
}return <main className="clientMain"><div className="clientPageTitle"><button className="clientBack" onClick={back}>‹</button><div><small>MÜVEKKİL</small><h1>{c.name}</h1></div><button onClick={edit}>Düzenle</button></div><section className="clientHero"><div><small>Vadesi gelen hizmet + masraf bakiyesi</small><h2 className={balance>0?'bad':'good'}>{TL(balance)}</h2></div><div className="clientMiniGrid"><K label="Hizmet bakiyesi" value={TL(c.feeBalance)}/><K label="Masraf bakiyesi" value={TL(c.expenseBalance)}/></div></section><section className="clientInfo"><p><b>İş:</b> {c.workType||'—'}</p><p><b>Başlangıç:</b> {trDate(c.startDate)}</p><p><b>İlk ödeme:</b> {trDate(c.firstDueDate)}</p><p><b>Ücret:</b> {c.feeType==='fixed'?TL(c.fixedAmount):`${c.multiplier??1} × asgari ücret + %${c.vatRate??settings.vatRate} KDV`} · <strong>{TL(fee(c,settings))}</strong></p>{c.notes&&<p><b>Dahili not:</b> {c.notes}</p>}</section><div className="clientDocActions"><button className="clientPrimary" disabled={exporting} onClick={()=>exportDocument(makePdf)}>PDF Cari Hesap</button><button disabled={exporting} onClick={()=>exportDocument(makeExcel)}>Excel Cari Hesap</button></div>{exporting&&<p role="status">Belge hazırlanıyor…</p>}{exportError&&<p role="alert">{exportError}</p>}<Expenses c={c} day={day} edit={expenseEdit} exportDocument={exportDocument} exporting={exporting}/><section><div className="clientSectionHead"><h2>Ödeme Dönemleri</h2><span>{c.ps.length} dönem</span></div>{!c.ps.length&&<p className="clientEmpty">Henüz başlamış bir hizmet dönemi yok.</p>}{visiblePeriods.map(p=><button className="periodRow" key={p.key} onClick={()=>periodEdit({client:c,period:p})}><div><b>{trDate(p.start)} – {trDate(p.end)}</b><small>Vade: {trDate(p.due)}{p.invoiceDate?` · Fatura: ${trDate(p.invoiceDate)}`:''}</small></div><div><strong>{TL(p.amount)}</strong><span className={'status '+p.status}>{statusLabel(p.status)}</span>{p.paidAmount>0&&<small>{TL(p.paidAmount)} ödendi{p.paymentDate?` · ${trDate(p.paymentDate)}`:''}</small>}</div></button>)}{visibleCount<c.ps.length&&<button className="clientLoadMore wide" onClick={()=>setVisibleCount(n=>n+PAGE_SIZE)}>Daha fazla dönem göster ({c.ps.length-visibleCount} kalan)</button>}</section></main>});
function ClientForm({initial,settings,close,save}){const[f,setF]=useState({id:initial.id||'',name:initial.name||'',workType:initial.workType||'Aylık Hukuki Danışmanlık',startDate:initial.startDate||today(),firstDueDate:initial.firstDueDate||addMonths(today(),1),feeType:initial.feeType||'minimum',multiplier:initial.multiplier??1.5,minimumWage:initial.minimumWage??settings.minimumWage,vatRate:initial.vatRate??settings.vatRate,fixedAmount:initial.fixedAmount||'',active:initial.active!==false,notes:initial.notes||''}),[error,setError]=useState('');function submit(){if(!f.name.trim()||!validDate(f.startDate)||!validDate(f.firstDueDate)||f.firstDueDate<=f.startDate){setError('Adı ve tarihleri kontrol edin. İlk ödeme başlangıçtan sonra olmalı.');return;}const fields=f.feeType==='fixed'?[f.fixedAmount]:[f.multiplier,f.minimumWage,f.vatRate];if(fields.some(v=>v===''||!Number.isFinite(Number(v))||Number(v)<0)){setError('Ücret alanlarına geçerli, negatif olmayan değerler girin.');return;}save({...f,name:f.name.trim()});}return <Modal title={initial.id?'Müvekkili Düzenle':'Yeni Müvekkil'} close={close}><label>Müvekkil adı<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>İş / hizmet<input value={f.workType} onChange={e=>setF({...f,workType:e.target.value})}/></label><div className="clientTwo"><label>İşe başlangıç<input type="date" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/></label><label>İlk ödeme<input type="date" value={f.firstDueDate} onChange={e=>setF({...f,firstDueDate:e.target.value})}/></label></div><label>Ücret modeli<select value={f.feeType} onChange={e=>setF({...f,feeType:e.target.value})}><option value="minimum">Asgari ücret katsayısı + KDV</option><option value="fixed">Sabit TL</option></select></label>{f.feeType==='minimum'?<><div className="clientTwo"><label>Katsayı<input type="number" step="0.1" value={f.multiplier} onChange={e=>setF({...f,multiplier:e.target.value})}/></label><label>KDV %<input type="number" value={f.vatRate} onChange={e=>setF({...f,vatRate:e.target.value})}/></label></div><label>Asgari ücret baz tutarı<input type="number" value={f.minimumWage} onChange={e=>setF({...f,minimumWage:e.target.value})}/></label></>:<label>Aylık sabit tutar<input type="number" value={f.fixedAmount} onChange={e=>setF({...f,fixedAmount:e.target.value})}/></label>}<label>Dahili not<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><label className="clientCheck"><input type="checkbox" checked={f.active} onChange={e=>setF({...f,active:e.target.checked})}/> Aktif müvekkil</label><button className="clientPrimary wide" disabled={!f.name||!f.startDate||!f.firstDueDate} onClick={submit}>Kaydet</button>{error&&<p role="alert">{error}</p>}</Modal>}
function PeriodForm({data,close,save}){const p=data.period,[f,setF]=useState({amount:p.amount,paidAmount:p.paidAmount||'',paymentDate:p.paymentDate||'',invoiceIssued:!!p.invoiceIssued,invoiceDate:p.invoiceDate||'',invoiceNo:p.invoiceNo||'',note:p.note||''}),[error,setError]=useState('');function submit(){if([f.amount,f.paidAmount].some(v=>!Number.isFinite(Number(v))||Number(v)<0)){setError('Tutarlar negatif olamaz.');return;}if((Number(f.paidAmount)>0&&!validDate(f.paymentDate))||(f.invoiceIssued&&!validDate(f.invoiceDate))){setError('Ödeme / fatura tarihini girin.');return;}save({...f,amount:money(f.amount),paidAmount:money(f.paidAmount)});}return <Modal title={`${trDate(p.start)} – ${trDate(p.end)}`} close={close}><label>Dönem tutarı<input type="number" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Ödenen tutar<input type="number" value={f.paidAmount} onChange={e=>setF({...f,paidAmount:e.target.value})}/></label><label>Ödeme tarihi<input type="date" value={f.paymentDate} onChange={e=>setF({...f,paymentDate:e.target.value})}/></label><label className="clientCheck"><input type="checkbox" checked={f.invoiceIssued} onChange={e=>setF({...f,invoiceIssued:e.target.checked})}/> Fatura kesildi</label>{f.invoiceIssued&&<div className="clientTwo"><label>Fatura tarihi<input type="date" value={f.invoiceDate} onChange={e=>setF({...f,invoiceDate:e.target.value})}/></label><label>Fatura no<input value={f.invoiceNo} onChange={e=>setF({...f,invoiceNo:e.target.value})}/></label></div>}<label>Dahili dönem notu<textarea value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></label><button className="clientPrimary wide" onClick={submit}>Kaydet</button>{error&&<p role="alert">{error}</p>}</Modal>}
function Modal({title,close,children}){return <div className="clientModalBg" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="clientModal" role="dialog" aria-modal="true" aria-label={title}><div className="clientModalHead"><h2>{title}</h2><button onClick={close}>✕</button></div>{children}</div></div>}

const Expenses=memo(function Expenses({c,day,edit,exportDocument,exporting}){
  const [month,setMonth]=useState(day.slice(0,7));
  const entries=useMemo(()=>expensesFor(c,day,month),[c,day,month]);
  const total=money(entries.reduce((s,e)=>s+e.amount,0)),paid=money(entries.reduce((s,e)=>s+e.paidAmount,0));
  return <section className="clientExpenses"><div className="clientSectionHead"><h2>Hukuki masraflar</h2><button className="clientPrimary" onClick={()=>edit({clientId:c.id})}>＋ Masraf ekle</button></div>
    <div className="expenseToolbar"><label>Masraf ayı<input type="month" value={month} onChange={e=>setMonth(e.target.value||day.slice(0,7))}/></label><div><small>Ay toplamı</small><b>{TL(total)}</b><small>Alınan: {TL(paid)} · Kalan: {TL(total-paid)}</small></div></div>
    {!entries.length&&<p className="clientEmpty">Bu ay için kayıtlı masraf yok.</p>}
    {entries.map(e=><button className="expenseRow" key={e.id} onClick={()=>edit({clientId:c.id,expense:e})}><div><b>{e.description}</b><small>{trDate(e.date)}</small></div><div><strong>{TL(e.amount)}</strong>{e.paidAmount>0&&<small>{TL(e.paidAmount)} alındı</small>}<small>Düzenle</small></div></button>)}
    <button disabled={!entries.length||exporting} onClick={()=>exportDocument((client,settings)=>makePdf(client,settings,{month,expensesOnly:true}))}>Bu ayın masraf PDF’i</button>
  </section>;
});
function ExpenseForm({initial,close,save}){
  const [f,setF]=useState(()=>({id:initial.id,date:initial.date||today(),description:initial.description||'',amount:initial.amount??'',paidAmount:initial.paidAmount??0})),[error,setError]=useState('');
  function submit(){const amount=money(f.amount),paidAmount=money(f.paidAmount);if(!validDate(f.date)||f.date>today()){setError('Gerçekleşen masrafın tarihini girin; gelecek tarih seçilemez.');return;}if(!f.description.trim()){setError('Masrafın ne için yapıldığını yazın.');return;}if(!Number.isFinite(Number(String(f.amount).replace(',','.')))||amount<=0||!Number.isFinite(Number(String(f.paidAmount).replace(',','.')))||paidAmount<0||paidAmount>amount){setError('Geçerli tutarlar girin. Alınan tutar masrafı aşamaz.');return;}save({...f,description:f.description.trim(),amount,paidAmount});}
  return <Modal title={initial.id?'Masrafı düzenle':'Hukuki masraf ekle'} close={close}>
    <label>Masraf tarihi<input type="date" max={today()} value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label>
    <label>Ne için yapıldı?<textarea placeholder="Örn. dosya harcı, tebligat, noter masrafı" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label>
    <label>Masraf tutarı (TL)<input inputMode="decimal" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label>
    <label>Müvekkilden alınan tutar (TL)<input inputMode="decimal" value={f.paidAmount} onChange={e=>setF({...f,paidAmount:e.target.value})}/></label>
    <p className="clientHint">Açıklama, tarih ve tutar müvekkile gönderilen PDF’te görünür.</p>
    {error&&<p role="alert">{error}</p>}<button className="clientPrimary wide" onClick={submit}>Kaydet</button>
  </Modal>;
}
