import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
import ClientTracker from'./clients-entry.jsx';
import{clientDefaults}from'./clients-domain.js';
import{APP_VERSION,TL,acc,accountStats,allTransactions,cat,categorySpend,carryCalc,inCurrentWeek,isReferenced,makeInstallment,next30DaysObligations,normalizeData,pRange,periodRange,periodFor,periodLabel,periodOf,purgeExpiredTrash,sum,today,uid,validAmount}from'./domain.js';
import{disableSecureStorage,enableSecureStorage,exportBackup,hasSecureStorage,loadPlainData,parseBackup,savePlainData,saveSecureData,unlockSecure}from'./storage.js';

const NAV=[['dash','⌂','Özet'],['tx','⇅','İşlemler'],['plans','◫','Planlar'],['report','▥','Rapor'],['settings','⚙','Ayarlar']];

function Boot(){
 const[locked,setLocked]=useState(()=>{try{return hasSecureStorage()}catch{return false}}),[data,setDataState]=useState(null),[saveState,setSaveState]=useState('saved'),[bootError,setBootError]=useState('');
 const dataRef=useRef(null),pinRef=useRef(''),revision=useRef(0);
 const persist=useCallback(async(next)=>{const rev=++revision.current;setSaveState('saving');let ok=false;try{ok=hasSecureStorage()?pinRef.current?await saveSecureData(next,pinRef.current):false:savePlainData(next)}catch{}if(rev===revision.current)setSaveState(ok?'saved':'error');return ok},[]);
 const setData=useCallback(update=>{const next=typeof update==='function'?update(dataRef.current):update;dataRef.current=next;setDataState(next);void persist(next)},[persist]);
 useEffect(()=>{if(locked||dataRef.current)return;try{setData(loadPlainData())}catch(e){setBootError(e.message)}},[locked,setData]);
 useEffect(()=>{if(saveState==='saved')return;const prevent=e=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[saveState]);
 async function unlock(v){try{const d=await unlockSecure(v);pinRef.current=v;dataRef.current=d;setDataState(d);setLocked(false);void persist(d);return true}catch{return false}}
 async function enableLock(v){++revision.current;setSaveState('saving');try{await enableSecureStorage(dataRef.current,v);pinRef.current=v;setSaveState('saved')}catch(e){setSaveState('error');throw e}}
 async function disableLock(){++revision.current;setSaveState('saving');try{await disableSecureStorage(dataRef.current);pinRef.current='';setSaveState('saved')}catch(e){setSaveState('error');throw e}}
 async function lockNow(){if(!hasSecureStorage())return;if(!await persist(dataRef.current))return;dataRef.current=null;setDataState(null);pinRef.current='';setLocked(true)}
 if(locked)return <LockScreen unlock={unlock}/>;
 if(bootError)return <div className="lock"><h1>Veri okunamadı</h1><p role="alert">{bootError}</p><button onClick={()=>window.location.reload()}>Tekrar dene</button></div>;
 if(!data)return <Splash/>;
 return <><App data={data} setData={setData} saveState={saveState} enableLock={enableLock} disableLock={disableLock} lockNow={lockNow}/>{saveState==='error'&&<div className="saveError" role="alert">Kaydedilemedi. Bu sayfayı kapatmadan tekrar deneyin.<button onClick={()=>persist(dataRef.current)}>Tekrar kaydet</button></div>}</>;
}

function Splash(){return <div className="splash"><div className="brandMark">BT</div><b>Budget Tracking</b><span>Finansal hafızan hazırlanıyor…</span></div>}
function LockScreen({unlock}){const[p,setP]=useState(''),[err,setErr]=useState('');async function go(){setErr('');if(!await unlock(p))setErr('PIN yanlış.')}return <div className="lock"><div className="brandMark">BT</div><h1>BT Kilitli</h1><p>Finans verilerin cihazda şifreli saklanıyor.</p><input autoFocus type="password" inputMode="numeric" placeholder="PIN" value={p} onChange={e=>setP(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/>{err&&<div className="errorText">{err}</div>}<button className="primary" onClick={go}>Kilidi Aç</button><small>PIN unutulursa şifreli verinin kurtarma anahtarı yoktur.</small></div>}

function App({data,setData,saveState,enableLock,disableLock,lockNow}){
 const[tab,setTab]=useState('dash'),[view,setView]=useState('aylik'),[off,setOff]=useState(0),[modal,setModal]=useState(null),[search,setSearch]=useState(''),[toast,setToast]=useState(null);
 const save=f=>setData(d=>normalizeData({...d,...f(d)}));
 const setClientState=useCallback(update=>setData(d=>({...d,clientTracker:typeof update==='function'?update(d.clientTracker||clientDefaults):update})),[setData]);
 const [currentDay,setCurrentDay]=useState(today);
 useEffect(()=>{const refresh=()=>setCurrentDay(today());const t=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(t);window.removeEventListener('focus',refresh)}},[]);
 const dayFor=(y,m)=>data.settings.overrides?.[`${y}-${m}`]||data.settings.periodDay;
 const now=periodFor(today(),data.settings);let gy=now.y,gm=now.m+off;while(gm<0){gm+=12;gy--}while(gm>11){gm-=12;gy++}const[ps,pe]=periodRange(gy,gm,data.settings);
 const txAll=useMemo(()=>allTransactions(data),[data.tx,data.installments,data.recurring]);
 const periodRows=useMemo(()=>txAll.filter(t=>view==='gunluk'?t.date===currentDay:view==='haftalik'?inCurrentWeek(t.date):t.date>=ps&&t.date<=pe),[txAll,view,ps,pe,currentDay]);
 const visible=useMemo(()=>periodRows.filter(t=>!search||`${t.note||''} ${cat(data,t.cat).label} ${acc(data,t.acc).name}`.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))),[periodRows,search,data]);
 const monthlyRows=useMemo(()=>txAll.filter(t=>t.date>=ps&&t.date<=pe),[txAll,ps,pe]);
 const monthlyCarry=useMemo(()=>carryCalc(txAll,gy,gm,data),[txAll,gy,gm,data.settings]);
 const income=sum(periodRows,'gelir'),expense=sum(periodRows,'gider'),carry=view==='aylik'?monthlyCarry:0,balance=income+carry-expense;
 function flash(message,action){setToast({message,action});setTimeout(()=>setToast(null),5000)}
 function addTx(x){save(d=>({tx:[{id:uid(),...x},...d.tx],prefs:{...d.prefs,lastAcc:x.acc,[x.type==='gider'?'lastExpenseCat':'lastIncomeCat']:x.cat}}))}
 function updateTx(id,x){save(d=>({tx:d.tx.map(t=>t.id===id?{...t,...x}:t)}))}
 function trash(kind,id){const key={tx:'tx',installment:'installments',recurring:'recurring'}[kind],payload=data[key]?.find(x=>x.id===id);if(!payload)return;save(d=>({[key]:d[key].filter(x=>x.id!==id),trash:[{id:uid(),kind,payload,deletedAt:new Date().toISOString()},...d.trash]}));flash('Kayıt çöp kutusuna taşındı.',()=>restoreTrash(payload,kind))}
 function restoreTrash(payload,kind){save(d=>{const map={tx:'tx',installment:'installments',recurring:'recurring'},key=map[kind];return{[key]:d[key].some(x=>x.id===payload.id)?d[key]:[payload,...d[key]],trash:d.trash.filter(x=>x.payload?.id!==payload.id)}});setToast(null)}
 function setInstallmentStatus(id,status){save(d=>({installments:d.installments.map(i=>i.id===id?{...i,status,completedAt:status==='active'?null:today()}:i)}))}
 function toggleRecurring(id){save(d=>({recurring:d.recurring.map(r=>r.id===id?{...r,active:r.active===false,pausedAt:r.active===false?null:today()}:r)}))}
 function goto(t){setTab(t);window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="appShell">
  <ClientTracker state={data.clientTracker||clientDefaults} setState={setClientState}/>
  <header className="appHeader"><div className="brandMark small">BT</div><div className="headText"><b>Budget Tracking</b><span>{view==='aylik'?`${periodLabel(gy,gm)} · ${ps.slice(8)}.${ps.slice(5,7)}–${pe.slice(8)}.${pe.slice(5,7)}`:'Kişisel finans hafızan'}</span></div><span className={`saveDot ${saveState}`} title={saveState==='error'?'Kaydedilemedi':saveState==='saving'?'Kaydediliyor':'Kaydedildi'}>●</span></header>
  <div className="content">
   {tab==='dash'&&<Dashboard data={data} list={periodRows} txAll={txAll} view={view} setView={setView} gy={gy} gm={gm} off={off} setOff={setOff} carry={carry} income={income} expense={expense} balance={balance} setModal={setModal} goto={goto}/>} 
   {tab==='tx'&&<Transactions data={data} list={visible} view={view} setView={setView} search={search} setSearch={setSearch} setModal={setModal} trash={trash}/>} 
   {tab==='plans'&&<Plans data={data} setModal={setModal} setInstallmentStatus={setInstallmentStatus} toggleRecurring={toggleRecurring} trash={trash}/>} 
   {tab==='report'&&<Report data={data} list={monthlyRows} txAll={txAll} gy={gy} gm={gm} carry={monthlyCarry}/>} 
   {tab==='settings'&&<Settings data={data} setData={setData} save={save} gy={gy} gm={gm} setModal={setModal} enableLock={enableLock} disableLock={disableLock} lockNow={lockNow} restoreTrash={restoreTrash}/>} 
  </div>
  <button className="fab" onClick={()=>setModal('tx')}>＋ İşlem</button>
  <nav className="bottomNav">{NAV.map(([id,ic,l])=><button key={id} className={tab===id?'on':''} onClick={()=>goto(id)}><span>{ic}</span><small>{l}</small></button>)}</nav>
  {modal==='tx'&&<TxForm data={data} close={()=>setModal(null)} addTx={addTx} addInst={i=>save(d=>({installments:[i,...d.installments]}))}/>} 
  {modal?.quick&&<TxForm data={data} close={()=>setModal(null)} presetCat={modal.quick.id} addTx={addTx} addInst={i=>save(d=>({installments:[i,...d.installments]}))}/>} 
  {modal?.editTx&&<TxForm data={data} close={()=>setModal(null)} initial={modal.editTx} update={updateTx}/>} 
  {modal==='rec'&&<RecurringForm data={data} close={()=>setModal(null)} saveRec={r=>save(d=>({recurring:[r,...d.recurring]}))}/>} 
  {modal?.editRec&&<RecurringForm data={data} close={()=>setModal(null)} initial={modal.editRec} saveRec={r=>save(d=>({recurring:d.recurring.map(x=>x.id===r.id?r:x)}))}/>} 
  {modal==='account'&&<EntityForm title="Hesap Ekle" kind="account" close={()=>setModal(null)} ok={v=>save(d=>({accounts:[...d.accounts,{id:uid(),kind:'custom',...v}]}))}/>} 
  {modal?.editAccount&&<EntityForm title="Hesabı Düzenle" kind="account" initial={modal.editAccount} close={()=>setModal(null)} ok={v=>save(d=>({accounts:d.accounts.map(a=>a.id===modal.editAccount.id?{...a,...v}:a)}))}/>} 
  {modal==='cat'&&<CategoryForm close={()=>setModal(null)} ok={v=>save(d=>({cats:[...d.cats,{id:uid(),...v}]}))}/>} 
  {modal?.editCat&&<CategoryForm initial={modal.editCat} close={()=>setModal(null)} ok={v=>save(d=>({cats:d.cats.map(c=>c.id===modal.editCat.id?{...c,...v}:c)}))}/>} 
  {toast&&<div className="toast"><span>{toast.message}</span>{toast.action&&<button onClick={toast.action}>Geri Al</button>}</div>}
 </div>
}

function PeriodControls({view,setView,gy,gm,off,setOff}){return <><div className="seg">{[['gunluk','Günlük'],['haftalik','Haftalık'],['aylik','Aylık']].map(([id,l])=><button key={id} className={view===id?'on':''} onClick={()=>setView(id)}>{l}</button>)}</div>{view==='aylik'&&<div className="periodSwitch"><button onClick={()=>setOff(off-1)}>‹</button><b>{periodLabel(gy,gm)}</b><button disabled={off>=0} onClick={()=>setOff(Math.min(0,off+1))}>›</button></div>}</>}
function KPI({title,value,tone,sub}){return <div className="kpiCard"><small>{title}</small><b className={tone||''}>{value}</b>{sub&&<span>{sub}</span>}</div>}
function Dashboard({data,list,txAll,view,setView,gy,gm,off,setOff,carry,income,expense,balance,setModal,goto}){
 const insights=makeInsights(data,list,txAll,gy,gm),topCats=mostUsedCategories(data),accounts=accountStats(data,list).slice(0,3),next=next30DaysObligations(data).slice(0,3);
 return <main><PeriodControls {...{view,setView,gy,gm,off,setOff}}/><section className="balanceHero"><div><small>Net bakiye</small><h1 className={balance>=0?'green':'red'}>{TL(balance)}</h1>{carry>0&&<span>↪ {TL(carry)} devretti</span>}</div><button onClick={()=>goto('report')}>Rapor →</button><div className="heroGrid"><KPI title="Gelir" value={TL(income+carry)} tone="green"/><KPI title="Gider" value={TL(expense)} tone="red"/></div></section>
 <section className="memory"><div className="sectionHead"><div><small>BT HAFIZA</small><h2>Bu dönem ne oluyor?</h2></div><span className="localBadge">Cihazında hesaplanır</span></div><div className="memoryList">{insights.map((x,i)=><div key={i}><span>{x.icon}</span><p>{x.text}</p></div>)}</div></section>
 <section><div className="sectionHead"><h2>Hızlı ekle</h2><button className="linkBtn" onClick={()=>setModal('tx')}>Tümü</button></div><div className="quickGrid">{topCats.map(c=><button key={c.id} onClick={()=>setModal({quick:c})}><span>{c.icon}</span><small>{c.label}</small></button>)}<button onClick={()=>setModal('tx')}><span>＋</span><small>İşlem</small></button><button onClick={()=>setModal('rec')}><span>↻</span><small>Düzenli</small></button></div></section>
 {accounts.length>0&&<section><div className="sectionHead"><h2>Hesap görünümü</h2><button className="linkBtn" onClick={()=>goto('settings')}>Yönet</button></div><div className="accountStrip">{accounts.map(a=><div key={a.id}><span>{a.icon}</span><small>{a.name}</small><b className={a.net>=0?'green':'red'}>{TL(a.net)}</b></div>)}</div></section>}
 {next.length>0&&<section><div className="sectionHead"><h2>Önündeki 30 gün</h2><button className="linkBtn" onClick={()=>goto('plans')}>Planlar</button></div>{next.map(t=><div className="miniRow" key={t.id}><span>{cat(data,t.cat).icon}</span><div><b>{t.note?.replace(' · otomatik','')}</b><small>{t.date}</small></div><strong>{TL(t.amount)}</strong></div>)}</section>}
 <Distribution data={data} list={list}/><TxList data={data} list={list.slice(0,6)} compact/>
 </main>
}
function mostUsedCategories(data){const counts={};data.tx.forEach(t=>counts[t.cat]=(counts[t.cat]||0)+1);const rows=data.cats.filter(c=>c.type==='gider').sort((a,b)=>(counts[b.id]||0)-(counts[a.id]||0));return rows.slice(0,4)}
function makeInsights(data,list,txAll,gy,gm){
 const out=[],ex=sum(list,'gider'),rows=categorySpend(list);let py=gm===0?gy-1:gy,pm=gm===0?11:gm-1,[s,e]=periodRange(py,pm,data.settings),prev=txAll.filter(t=>t.date>=s&&t.date<=e),pex=sum(prev,'gider');
 if(pex){const d=(ex-pex)/pex*100;out.push({icon:d>5?'↗':'↘',text:`Giderin önceki döneme göre %${Math.abs(d).toFixed(0)} ${d>0?'daha yüksek':'daha düşük'}.`})}else out.push({icon:'◎',text:'Karşılaştırma için önceki dönem verisi henüz yeterli değil.'});
 if(rows[0])out.push({icon:cat(data,rows[0][0]).icon,text:`En büyük gider alanın ${cat(data,rows[0][0]).label}: ${TL(rows[0][1])}.`});
 const ob=next30DaysObligations(data),fixed=sum(ob,'gider');if(fixed>0)out.push({icon:'◷',text:`Önümüzdeki 30 günde planlı ${TL(fixed)} ödeme görünüyor.`});else out.push({icon:'✓',text:'Önümüzdeki 30 gün için kayıtlı planlı ödeme yok.'});
 return out.slice(0,3)
}

function Transactions({data,list,view,setView,search,setSearch,setModal,trash}){return <main><div className="pageTitle"><div><small>HAREKETLER</small><h1>İşlemler</h1></div><button onClick={()=>setModal('tx')}>＋</button></div><div className="search"><span>⌕</span><input placeholder="Kategori, hesap veya not ara" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="seg">{[['gunluk','Günlük'],['haftalik','Haftalık'],['aylik','Aylık']].map(([id,l])=><button key={id} className={view===id?'on':''} onClick={()=>setView(id)}>{l}</button>)}</div><TxList data={data} list={list} edit={t=>setModal({editTx:t})} trash={id=>trash('tx',id)}/></main>}
function TxList({data,list,edit,trash,compact=false}){return <section><div className="sectionHead"><h2>{compact?'Son işlemler':`İşlemler · ${list.length}`}</h2></div>{!list.length&&<Empty text="Bu görünümde işlem yok."/>}{list.map(t=><div className="txRow" key={t.id}><div className="txIcon">{cat(data,t.cat).icon}</div><div className="txInfo"><b>{cat(data,t.cat).label}</b><small>{t.date} · {acc(data,t.acc).icon} {acc(data,t.acc).name}{t.note?` · ${t.note}`:''}</small></div><strong className={t.type==='gelir'?'green':'red'}>{t.type==='gelir'?'+':'−'}{TL(t.amount)}</strong>{!compact&&!t.auto&&<div className="rowActions"><button onClick={()=>edit(t)}>✎</button><button onClick={()=>trash(t.id)}>⌫</button></div>}</div>)}</section>}

function Plans({data,setModal,setInstallmentStatus,toggleRecurring,trash}){const active=data.installments.filter(i=>i.status!=='completed'),done=data.installments.filter(i=>i.status==='completed');return <main><div className="pageTitle"><div><small>GELECEK</small><h1>Planlar</h1></div><button onClick={()=>setModal('rec')}>＋</button></div><section><div className="sectionHead"><h2>Taksitler</h2><span>{active.length} aktif</span></div>{!data.installments.length&&<Empty text="Taksitli işlem yok."/>}{[...active,...done].map(i=>{const past=i.items.filter(x=>x.date<today()).length,next=i.items.find(x=>x.date>=today()),pct=Math.min(100,Math.round(past/Math.max(1,i.items.length)*100));return <div className={`planCard ${i.status==='completed'?'mutedCard':''}`} key={i.id}><div className="planTop"><span>{cat(data,i.cat).icon}</span><div><b>{i.note||cat(data,i.cat).label}</b><small>{past}/{i.items.length} dönem · {i.status==='completed'?'tamamlandı':next?`sıradaki ${next.date}`:'sonlandı'}</small></div><strong>{next?TL(next.amount):TL(i.amount)}</strong></div><div className="progress"><i style={{width:pct+'%'}}/></div><details><summary>Plan ayrıntısı</summary>{i.items.map((x,k)=><p className="planLine" key={k}><span>{x.date<today()?'✓':'○'} {k+1}. taksit</span><span>{x.date}</span><b>{TL(x.amount)}</b></p>)}</details><div className="planActions"><button onClick={()=>setInstallmentStatus(i.id,i.status==='completed'?'active':'completed')}>{i.status==='completed'?'Yeniden Aç':'Tamamla'}</button><button className="dangerGhost" onClick={()=>trash('installment',i.id)}>Sil</button></div></div>})}</section>
 <section><div className="sectionHead"><h2>Tekrarlayanlar</h2><button className="linkBtn" onClick={()=>setModal('rec')}>＋ Ekle</button></div>{!data.recurring.length&&<Empty text="Tekrarlayan işlem yok."/>}{data.recurring.map(r=><div className="recRow" key={r.id}><span>{cat(data,r.cat).icon}</span><div><b>{r.note||cat(data,r.cat).label}</b><small>{TL(r.amount)} · {r.count||24} ay · {r.active===false?'duraklatıldı':'aktif'}</small></div><button onClick={()=>toggleRecurring(r.id)}>{r.active===false?'▶':'Ⅱ'}</button><button onClick={()=>setModal({editRec:r})}>✎</button><button className="dangerGhost" onClick={()=>trash('recurring',r.id)}>⌫</button></div>)}</section></main>}

function Report({data,list,txAll,gy,gm,carry}){let py=gm===0?gy-1:gy,pm=gm===0?11:gm-1,[s,e]=periodRange(py,pm,data.settings),prev=txAll.filter(t=>t.date>=s&&t.date<=e),inc=sum(list,'gelir')+carry,ex=sum(list,'gider'),pex=sum(prev,'gider'),diff=pex?((ex-pex)/pex*100):null,rows=categorySpend(list),days=Math.max(1,new Set(list.map(x=>x.date)).size),daily=ex/days;return <main><div className="pageTitle"><div><small>ANALİZ</small><h1>Aylık Rapor</h1></div><span className="periodPill">{periodLabel(gy,gm)}</span></div><div className="reportGrid"><KPI title="Gelir + devir" value={TL(inc)} tone="green"/><KPI title="Gider" value={TL(ex)} tone="red"/><KPI title="Net" value={TL(inc-ex)} tone={inc-ex>=0?'green':'red'}/><KPI title="Aktif gün ort." value={TL(daily)}/></div><section className="compare"><span>{diff==null?'—':diff>0?'↗':'↘'}</span><div><small>Önceki döneme göre gider</small><b className={diff==null?'':diff>0?'red':'green'}>{diff==null?'Yeterli veri yok':`%${Math.abs(diff).toFixed(0)} ${diff>0?'artış':'azalış'}`}</b></div></section><BudgetView data={data} rows={rows}/><Distribution data={data} list={list}/><AccountReport data={data} list={list}/></main>}
function Distribution({data,list}){const rows=categorySpend(list),max=rows[0]?.[1]||1;if(!rows.length)return null;return <section><div className="sectionHead"><h2>Gider dağılımı</h2></div>{rows.slice(0,8).map(([id,v])=><div className="barRow" key={id}><div><span>{cat(data,id).icon}</span><b>{cat(data,id).label}</b><strong>{TL(v)}</strong></div><em><i style={{width:`${v/max*100}%`}}/></em></div>)}</section>}
function BudgetView({data,rows}){const budgetRows=rows.filter(([id])=>Number(data.budgets[id])>0);if(!budgetRows.length)return <section><div className="sectionHead"><h2>Bütçe takibi</h2></div><p className="subtle">Kategori bütçelerini Ayarlar bölümünden tanımladığında burada doluluk oranlarını görürsün.</p></section>;return <section><div className="sectionHead"><h2>Bütçe takibi</h2></div>{budgetRows.map(([id,v])=>{const b=Number(data.budgets[id]),pct=Math.round(v/b*100);return <div className="budgetRow" key={id}><div><b>{cat(data,id).icon} {cat(data,id).label}</b><span className={pct>100?'red':''}>{TL(v)} / {TL(b)}</span></div><em><i className={pct>100?'over':''} style={{width:`${Math.min(100,pct)}%`}}/></em></div>})}</section>}
function AccountReport({data,list}){return <section><div className="sectionHead"><h2>Hesap bazında</h2></div>{accountStats(data,list).map(a=><div className="miniRow" key={a.id}><span>{a.icon}</span><div><b>{a.name}</b><small>Gider {TL(a.expense)} · Gelir {TL(a.income)}</small></div><strong className={a.net>=0?'green':'red'}>{TL(a.net)}</strong></div>)}</section>}

function Settings({data,setData,save,gy,gm,setModal,enableLock,disableLock,lockNow,restoreTrash}){const key=`${gy}-${gm}`,[msg,setMsg]=useState('');const secure=hasSecureStorage();async function importFile(file){try{const text=await file.text(),next=parseBackup(text,data.clientTracker);setData(next);setMsg('Yedek doğrulandı ve yüklendi.')}catch(e){setMsg(e.message||'Yedek okunamadı.')}}async function setupPin(){const p=prompt('En az 4 haneli bir PIN belirle. Bu PIN unutulursa şifreli verinin kurtarma anahtarı yoktur.');if(!p)return;try{await enableLock(p);setMsg('Uygulama kilidi ve cihaz içi şifreleme açıldı.')}catch(e){setMsg(e.message)}}async function removePin(){if(!confirm('Uygulama kilidi kapatılsın mı? Veriler tekrar normal cihaz depolamasında saklanacak.'))return;try{await disableLock();setMsg('Uygulama kilidi kapatıldı.')}catch(e){setMsg(e.message)}}function deleteEntity(kind,id){if(isReferenced(data,kind,id)){setMsg('Bu kayıt geçmiş işlemlerde kullanılıyor. Veri bütünlüğü için silinmedi.');return}if(kind==='cat')save(d=>({cats:d.cats.filter(c=>c.id!==id),budgets:Object.fromEntries(Object.entries(d.budgets).filter(([k])=>k!==id))}));else save(d=>({accounts:d.accounts.filter(a=>a.id!==id)}))}
 return <main><div className="pageTitle"><div><small>SİSTEM</small><h1>Ayarlar</h1></div><span className="version">v{APP_VERSION}</span></div>{msg&&<div className="notice">{msg}</div>}<section><h2>Dönem</h2><label>Varsayılan başlangıç günü</label><input type="number" min="1" max="28" value={data.settings.periodDay} onChange={e=>save(d=>({settings:{...d.settings,periodDay:Number(e.target.value)}}))}/><label>{periodLabel(gy,gm)} özel başlangıç günü</label><div className="inline"><input type="number" min="1" max="28" value={data.settings.overrides[key]||data.settings.periodDay} onChange={e=>save(d=>({settings:{...d.settings,overrides:{...d.settings.overrides,[key]:Number(e.target.value)}}}))}/><button onClick={()=>save(d=>{const o={...d.settings.overrides};delete o[key];return{settings:{...d.settings,overrides:o}}})}>Sıfırla</button></div></section>
 <section><div className="sectionHead"><h2>Hesaplar</h2><button className="linkBtn" onClick={()=>setModal('account')}>＋ Ekle</button></div>{data.accounts.map(a=><div className="manageRow" key={a.id}><span>{a.icon}</span><b>{a.name}</b><button onClick={()=>setModal({editAccount:a})}>Düzenle</button>{!['nakit','kart'].includes(a.id)&&<button className="dangerGhost" onClick={()=>deleteEntity('acc',a.id)}>Sil</button>}</div>)}</section>
 <section><div className="sectionHead"><h2>Kategoriler</h2><button className="linkBtn" onClick={()=>setModal('cat')}>＋ Ekle</button></div><div className="manageList">{data.cats.map(c=><div className="manageRow" key={c.id}><span>{c.icon}</span><b>{c.label}</b><small>{c.type==='gider'?'Gider':'Gelir'}</small><button onClick={()=>setModal({editCat:c})}>Düzenle</button>{!defaultIds.has(c.id)&&<button className="dangerGhost" onClick={()=>deleteEntity('cat',c.id)}>Sil</button>}</div>)}</div></section>
 <section><h2>Kategori bütçeleri</h2><p className="subtle">0 bıraktığın kategori raporda bütçe takibine girmez.</p>{data.cats.filter(c=>c.type==='gider').map(c=><div className="budgetEdit" key={c.id}><span>{c.icon} {c.label}</span><input inputMode="decimal" placeholder="0" value={data.budgets[c.id]||''} onChange={e=>save(d=>({budgets:{...d.budgets,[c.id]:Number(String(e.target.value).replace(',','.'))||0}}))}/></div>)}</section>
 <section><h2>Gizlilik ve kilit</h2><p className="subtle">Kilit açıldığında BT verileri AES-GCM ile cihazda şifreli saklar; PIN yalnızca bu oturumun belleğinde tutulur.</p>{secure?<><button className="primary" onClick={lockNow}>Şimdi Kilitle</button><button onClick={removePin}>Kilidi Kapat</button></>:<button className="primary" onClick={setupPin}>PIN + Şifreleme Aç</button>}</section>
 <section><h2>Yedekleme</h2><div className="settingsGrid"><button onClick={()=>exportBackup(data)}>Yedek İndir</button><label className="upload">Yedek Yükle<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label></div></section>
 <Trash data={data} save={save} restoreTrash={restoreTrash}/></main>}
const defaultIds=new Set(['market','kira','elektrik','su','dogalgaz','internet','telefon','aidat','diger_fatura','ulasim','akaryakit','saglik','eglence','giyim','restoran','egitim','abonelik','ev_esyasi','kisisel_bakim','evcil_hayvan','hediye','seyahat','spor','vergi_borc','bagis','diger_gider','maas','ek_gelir','yatirim','diger_gelir']);
function Trash({data,save,restoreTrash}){const rows=purgeExpiredTrash(data.trash);return <section><div className="sectionHead"><h2>Çöp Kutusu</h2><span>{rows.length}/30 gün</span></div>{!rows.length&&<p className="subtle">Silinen kayıt yok.</p>}{rows.map(x=><div className="trashRow" key={x.id}><div><b>{x.kind==='tx'?'İşlem':x.kind==='installment'?'Taksit':'Tekrarlayan'}</b><small>{x.payload?.note||x.payload?.date||'Kayıt'}</small></div><button onClick={()=>restoreTrash(x.payload,x.kind)}>Geri Yükle</button><button className="dangerGhost" onClick={()=>save(d=>({trash:d.trash.filter(t=>t.id!==x.id)}))}>Kalıcı Sil</button></div>)}</section>}

function TxForm({data,close,addTx,initial,update,addInst,presetCat}){const preset=data.cats.find(c=>c.id===presetCat);const[f,setF]=useState(initial?{...initial,mode:'one'}:{type:preset?.type||'gider',cat:preset?.id||data.prefs.lastExpenseCat||'market',acc:data.prefs.lastAcc||data.accounts[0]?.id,amount:'',date:today(),note:'',mode:'one',count:2}),[err,setErr]=useState('');const cats=data.cats.filter(c=>c.type===f.type);function switchType(type){setF(x=>({...x,type,cat:type==='gider'?(data.prefs.lastExpenseCat||'market'):(data.prefs.lastIncomeCat||'maas')}))}function submit(){setErr('');if(!validAmount(f.amount)){setErr('Tutar 0’dan büyük olmalı.');return}if(!f.date){setErr('Tarih gerekli.');return}if(!data.cats.some(c=>c.id===f.cat&&c.type===f.type)||!data.accounts.some(a=>a.id===f.acc)){setErr('Geçerli bir kategori ve hesap seçin.');return;}if(f.mode==='inst'&&!initial){if(!Number.isInteger(Number(f.count))||Number(f.count)<2||Number(f.count)>240){setErr('Taksit sayısı 2–240 arasında bir tam sayı olmalı.');return}addInst(makeInstallment({...f,amount:Number(String(f.amount).replace(',','.'))}));close();return}const x={type:f.type,cat:f.cat,acc:f.acc,amount:Number(String(f.amount).replace(',','.')),date:f.date,note:f.note||''};initial?update(initial.id,x):addTx(x);close()}return <Modal title={initial?'İşlemi Düzenle':'Yeni İşlem'} close={close}><div className="seg"><button className={f.type==='gider'?'on':''} onClick={()=>switchType('gider')}>Gider</button><button className={f.type==='gelir'?'on':''} onClick={()=>switchType('gelir')}>Gelir</button></div>{!initial&&<div className="seg"><button className={f.mode==='one'?'on':''} onClick={()=>setF({...f,mode:'one'})}>Tek</button><button className={f.mode==='inst'?'on':''} onClick={()=>setF({...f,mode:'inst'})}>Taksitli</button></div>}<label>Kategori</label><select value={f.cat} onChange={e=>setF({...f,cat:e.target.value})}>{cats.map(c=><option key={c.id} value={c.id}>{c.icon} {c.label}</option>)}</select><label>Hesap</label><select value={f.acc} onChange={e=>setF({...f,acc:e.target.value})}>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.icon} {a.name}</option>)}</select><label>Tutar</label><input inputMode="decimal" placeholder="0,00" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/>{f.mode==='inst'&&<><label>Taksit sayısı</label><input type="number" min="2" value={f.count} onChange={e=>setF({...f,count:e.target.value})}/></>}<label>Tarih</label><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/><label>Not</label><input placeholder="İsteğe bağlı" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/>{f.mode==='inst'&&validAmount(f.amount)&&Number(f.count)>1&&<p className="hint">Yaklaşık aylık: {TL(Number(String(f.amount).replace(',','.'))/Number(f.count))}</p>}{err&&<div className="errorText">{err}</div>}<button className="primary" onClick={submit}>Kaydet</button></Modal>}
function RecurringForm({data,close,initial,saveRec}){const[f,setF]=useState(initial||{id:uid(),type:'gider',cat:'abonelik',acc:data.prefs.lastAcc||data.accounts[0]?.id,amount:'',start:today(),count:12,note:'',active:true}),[err,setErr]=useState('');function go(){if(!validAmount(f.amount)){setErr('Geçerli bir tutar gir.');return}if(!data.cats.some(c=>c.id===f.cat&&c.type===f.type)||!data.accounts.some(a=>a.id===f.acc)){setErr('Geçerli kategori ve hesap seçin.');return;}if(!f.start||!Number.isInteger(Number(f.count))||Number(f.count)<1||Number(f.count)>240){setErr('Başlangıç tarihi ve 1–240 arasında tam ay sayısı girin.');return;}saveRec({...f,amount:Number(String(f.amount).replace(',','.')),count:Math.max(1,Number(f.count)||12)});close()}return <Modal title={initial?'Tekrarlayanı Düzenle':'Tekrarlayan İşlem'} close={close}><select value={f.type} onChange={e=>setF({...f,type:e.target.value,cat:e.target.value==='gelir'?'maas':'abonelik'})}><option value="gider">Gider</option><option value="gelir">Gelir</option></select><select value={f.cat} onChange={e=>setF({...f,cat:e.target.value})}>{data.cats.filter(c=>c.type===f.type).map(c=><option key={c.id} value={c.id}>{c.icon} {c.label}</option>)}</select><select value={f.acc} onChange={e=>setF({...f,acc:e.target.value})}>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.icon} {a.name}</option>)}</select><input inputMode="decimal" placeholder="Tutar" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><label>Başlangıç</label><input type="date" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/><label>Kaç ay</label><input type="number" min="1" max="240" value={f.count} onChange={e=>setF({...f,count:e.target.value})}/><input placeholder="Not" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/>{err&&<div className="errorText">{err}</div>}<button className="primary" onClick={go}>Kaydet</button></Modal>}
function EntityForm({title,kind,initial,ok,close}){const[v,setV]=useState(initial||{icon:kind==='account'?'🏦':'🏷️',name:''});return <Modal title={title} close={close}><input placeholder="İkon" value={v.icon||''} onChange={e=>setV({...v,icon:e.target.value})}/><input placeholder="Hesap adı" value={v.name||''} onChange={e=>setV({...v,name:e.target.value})}/><button className="primary" disabled={!v.name?.trim()} onClick={()=>{ok({icon:v.icon||'🏦',name:v.name.trim()});close()}}>Kaydet</button></Modal>}
function CategoryForm({initial,ok,close}){const[f,setF]=useState(initial||{type:'gider',icon:'🏷️',label:''});return <Modal title={initial?'Kategoriyi Düzenle':'Kategori Ekle'} close={close}><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="gider">Gider</option><option value="gelir">Gelir</option></select><input placeholder="İkon" value={f.icon} onChange={e=>setF({...f,icon:e.target.value})}/><input placeholder="Kategori adı" value={f.label} onChange={e=>setF({...f,label:e.target.value})}/><button className="primary" disabled={!f.label.trim()} onClick={()=>{ok({type:f.type,icon:f.icon||'🏷️',label:f.label.trim()});close()}}>Kaydet</button></Modal>}
function Modal({title,children,close}){return <div className="overlay" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="grab"/><div className="modalHead"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function Empty({text}){return <div className="empty"><span>○</span><p>{text}</p></div>}

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
createRoot(document.getElementById('root')).render(<Boot/>);
